### ISSUE TITLE
After v4 Deployment Checklist

### ISSUE THREAD

**Issue by AirFusion45** [AirFusion45/db8bot#334]
- [x] PR v4.0.0 to master
- [x] add {legacy} in telemetry for legacy cmd execs
- [x] Get data off of old instance & shut it down
- [x] cite https://github.com/iamadamdev/bypass-paywalls-chrome/
- [x] Google Analytics Userid not showing, shows clientid
- [x] invite link in bot's profile - add on discord.com/developers
- [x] create github release
- [x] change bot playing status to /help
- [x] for goodness sakes get sentry on the bot rn

**Comment by AirFusion45** [comment]
xvfb fix:

https://stackoverflow.com/questions/51883055/running-puppeteer-with-xfvb-headless-false

OR 

on init docker img, create sh script that starts an xvfb server BEFORE nodejs runs - that way puppeteer can just choose to adopt the single available display. 

Also make sure to implement shell cmd removing /tmp/x.99 file

**Comment by AirFusion45** [comment]
fixed in https://github.com/AirFusion45/db8bot/commit/f7a12fb1c1b7fe6980d3568ad5250f359f035cd0
